version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT:-3000}
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.lifecycle.pre-update=docker exec leastric-fe-app-1 sh -c 'echo Pre-update hook executed'"
      - "com.centurylinklabs.watchtower.lifecycle.post-update=docker exec leastric-fe-app-1 sh -c 'echo Post-update hook executed'"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${APP_PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_PORT:-3001}:${APP_PORT:-3001}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    profiles:
      - dev