version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT:-3000}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.lifecycle.pre-update=docker exec leastric-fe-app-1 sh -c 'echo Pre-update hook executed'"
      - "com.centurylinklabs.watchtower.lifecycle.post-update=docker exec leastric-fe-app-1 sh -c 'echo Post-update hook executed'"
    networks:
      - frontend-leastric-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${APP_PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # watchtower:
  #   image: containrrr/watchtower:latest
  #   container_name: leastric-frontend-watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /root/.docker/config.json:/config.json:ro
  #   environment:
  #     # Core Watchtower configuration
  #     WATCHTOWER_CLEANUP: "true"
  #     WATCHTOWER_REMOVE_VOLUMES: "false" 
  #     WATCHTOWER_INCLUDE_STOPPED: "false"
  #     WATCHTOWER_INCLUDE_RESTARTING: "true"
  #     WATCHTOWER_POLL_INTERVAL: "30"      # Check every 5 minutes
  #     WATCHTOWER_TIMEOUT: "45s"           # Wait 45s for container to stop
  #     WATCHTOWER_ROLLING_RESTART: "true"  # Update one container at a time
  #     WATCHTOWER_NO_STARTUP_MESSAGE: "false"
  #     WATCHTOWER_DEBUG: "true"
  #     # Only monitor containers with the watchtower.enable=true label
  #     WATCHTOWER_LABEL_ENABLE: "true"
  #     # Lifecycle hooks for pre/post update actions
  #     WATCHTOWER_LIFECYCLE_HOOKS: "true"
  #   # Notification settings (optional)
  #     # WATCHTOWER_NOTIFICATIONS: "${WATCHTOWER_NOTIFICATIONS:-}"
  #     # WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "${SLACK_WEBHOOK_URL:-}"
  #     # WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "Leastric Staging Watchtower"
  #     # WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#deployments"
  #   command: >
  #     --cleanup
  #     --remove-volumes=false
  #     --include-stopped=false
  #     --include-restarting=true
  #     --rolling-restart=true
  #     --stop-timeout=45s
  #     --label-enable
  #     --debug
  #   restart: unless-stopped
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"  # Don't watch watchtower itself
  #   networks:
  #     - frontend-leastric-network

networks:
  frontend-leastric-network:
    name: leastric-global-network
    external: true